/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AppLink: typeof import('./../layout/components/AppLink/index.vue')['default']
    Breadcrumb: typeof import('./../components/Breadcrumb/index.vue')['default']
    ElBreadcrumb: typeof import('element-plus/es')['ElBreadcrumb']
    ElBreadcrumbItem: typeof import('element-plus/es')['ElBreadcrumbItem']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElCard: typeof import('element-plus/es')['ElCard']
    ElConfigProvider: typeof import('element-plus/es')['ElConfigProvider']
    ElDropdown: typeof import('element-plus/es')['ElDropdown']
    ElDropdownItem: typeof import('element-plus/es')['ElDropdownItem']
    ElDropdownMenu: typeof import('element-plus/es')['ElDropdownMenu']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElImage: typeof import('element-plus/es')['ElImage']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElMenu: typeof import('element-plus/es')['ElMenu']
    ElMenuItem: typeof import('element-plus/es')['ElMenuItem']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSubMenu: typeof import('element-plus/es')['ElSubMenu']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    Hamburger: typeof import('./../components/Hamburger/index.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    IEpClose: typeof import('~icons/ep/close')['default']
    IEpInfoFilled: typeof import('~icons/ep/info-filled')['default']
    IEpSuccessFilled: typeof import('~icons/ep/success-filled')['default']
    IEpWarningFilled: typeof import('~icons/ep/warning-filled')['default']
    IEpWarnTriangleFilled: typeof import('~icons/ep/warn-triangle-filled')['default']
    LangSelect: typeof import('./../components/LangSelect/index.vue')['default']
    NavBar: typeof import('./../layout/components/NavBar/index.vue')['default']
    NavbarLeft: typeof import('./../layout/components/NavBar/components/NavbarLeft.vue')['default']
    NavbarRight: typeof import('./../layout/components/NavBar/components/NavbarRight.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Sidebar: typeof import('./../layout/components/Sidebar/index.vue')['default']
    SidebarLogo: typeof import('./../layout/components/Sidebar/components/SidebarLogo.vue')['default']
    SidebarMenu: typeof import('./../layout/components/Sidebar/components/SidebarMenu.vue')['default']
    SidebarMenuItem: typeof import('./../layout/components/Sidebar/components/SidebarMenuItem.vue')['default']
    SidebarMenuItemTitle: typeof import('./../layout/components/Sidebar/components/SidebarMenuItemTitle.vue')['default']
    SizeSelect: typeof import('./../components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    TagsView: typeof import('./../layout/components/TagsView/index.vue')['default']
  }
}
